[2023-03-25T14:19:49.716-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.spark_submit_task manual__2023-03-22T23:23:18.183116+00:00 [queued]>
[2023-03-25T14:19:49.721-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.spark_submit_task manual__2023-03-22T23:23:18.183116+00:00 [queued]>
[2023-03-25T14:19:49.721-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:19:49.721-0400] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-25T14:19:49.721-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:19:49.725-0400] {taskinstance.py:1303} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2023-03-22 23:23:18.183116+00:00
[2023-03-25T14:19:49.727-0400] {standard_task_runner.py:55} INFO - Started process 9113 to run task
[2023-03-25T14:19:49.729-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'spark_submit_task', 'manual__2023-03-22T23:23:18.183116+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp0nsys2nk']
[2023-03-25T14:19:49.730-0400] {standard_task_runner.py:83} INFO - Job 99: Subtask spark_submit_task
[2023-03-25T14:19:49.749-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.spark_submit_task manual__2023-03-22T23:23:18.183116+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-25T14:19:49.768-0400] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=spark_submit_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T23:23:18.183116+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T23:23:18.183116+00:00
[2023-03-25T14:19:49.770-0400] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-03-25T14:19:49.771-0400] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --queue root.default 
[2023-03-25T14:19:52.464-0400] {spark_submit.py:495} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-03-25T14:19:52.465-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2023-03-25T14:19:52.465-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2023-03-25T14:19:52.465-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2023-03-25T14:19:52.465-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2023-03-25T14:19:52.465-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2023-03-25T14:19:52.465-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2023-03-25T14:19:52.466-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2023-03-25T14:19:52.466-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2023-03-25T14:19:52.466-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2023-03-25T14:19:52.466-0400] {spark_submit.py:495} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-03-25T14:19:52.496-0400] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/Users/sunanda/Downloads/airflow/py_env/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 426, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default . Error code is: 1.
[2023-03-25T14:19:52.508-0400] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=api_dag, task_id=spark_submit_task, execution_date=20230322T232318, start_date=20230325T181949, end_date=20230325T181952
[2023-03-25T14:19:52.512-0400] {standard_task_runner.py:100} ERROR - Failed to execute job 99 for task spark_submit_task (Cannot execute: spark-submit --master yarn --name arrow-spark --queue root.default . Error code is: 1.; 9113)
[2023-03-25T14:19:52.547-0400] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T14:19:52.553-0400] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
