[2023-03-21T16:10:41.314-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.is_api_active scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-21T16:10:41.318-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.is_api_active scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-21T16:10:41.318-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T16:10:41.318-0400] {taskinstance.py:1283} INFO - Starting attempt 2 of 1
[2023-03-21T16:10:41.318-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-21T16:10:41.323-0400] {taskinstance.py:1303} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-19 00:00:00+00:00
[2023-03-21T16:10:41.325-0400] {standard_task_runner.py:55} INFO - Started process 41386 to run task
[2023-03-21T16:10:41.328-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpcag7qc4k']
[2023-03-21T16:10:41.328-0400] {standard_task_runner.py:83} INFO - Job 8: Subtask is_api_active
[2023-03-21T16:10:41.353-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active scheduled__2023-03-19T00:00:00+00:00 [running]> on host sunandas-laptop.local
[2023-03-21T16:10:41.372-0400] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-21T16:10:41.373-0400] {http.py:122} INFO - Poking: weather?q=Monroe,GA,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-21T16:10:41.375-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-21T20:23:14.918-0400] {local_task_job.py:238} ERROR - The recorded hostname sunandas-laptop.hsd1.ga.comcast.net does not match this instance's hostname sunandas-laptop.local
[2023-03-21T20:23:14.925-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 41386. PIDs of all processes in the group: [41386]
[2023-03-21T20:23:14.925-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 41386
[2023-03-21T20:24:14.953-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=41386, name='Python', status='running', started='16:10:41') did not respond to SIGTERM. Trying SIGKILL
[2023-03-21T20:24:14.954-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 41386
[2023-03-21T20:24:14.958-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=41386, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:10:41') (41386) terminated with exit code Negsignal.SIGKILL
[2023-03-21T20:24:14.958-0400] {standard_task_runner.py:168} ERROR - Job 11 was killed before it finished (likely due to running out of memory)
