[2023-03-22T19:38:30.629-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T20:21:55.627267+00:00 [queued]>
[2023-03-22T19:38:30.637-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: api_dag.is_api_active manual__2023-03-22T20:21:55.627267+00:00 [queued]>
[2023-03-22T19:38:30.637-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T19:38:30.637-0400] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-22T19:38:30.637-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T19:38:30.643-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_active> on 2023-03-22 20:21:55.627267+00:00
[2023-03-22T19:38:30.645-0400] {standard_task_runner.py:55} INFO - Started process 5778 to run task
[2023-03-22T19:38:30.649-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'api_dag', 'is_api_active', 'manual__2023-03-22T20:21:55.627267+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/weatherapi_test.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpkxtpkg58']
[2023-03-22T19:38:30.650-0400] {standard_task_runner.py:83} INFO - Job 74: Subtask is_api_active
[2023-03-22T19:38:30.673-0400] {task_command.py:388} INFO - Running <TaskInstance: api_dag.is_api_active manual__2023-03-22T20:21:55.627267+00:00 [running]> on host sunandas-laptop.hsd1.ga.comcast.net
[2023-03-22T19:38:30.695-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=api_dag
AIRFLOW_CTX_TASK_ID=is_api_active
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T20:21:55.627267+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T20:21:55.627267+00:00
[2023-03-22T19:38:30.696-0400] {http.py:122} INFO - Poking: weather?q=Monroe,GA,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T19:38:30.699-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T19:58:28.420-0400] {local_task_job.py:272} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-03-22T19:58:28.424-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 5778. PIDs of all processes in the group: [5778]
[2023-03-22T19:58:28.424-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5778
[2023-03-22T19:59:28.476-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=5778, name='Python', status='running', started='19:38:30') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T19:59:28.476-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 5778
[2023-03-22T19:59:28.479-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=5778, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='19:38:30') (5778) terminated with exit code Negsignal.SIGKILL
[2023-03-22T19:59:28.479-0400] {standard_task_runner.py:168} ERROR - Job 74 was killed before it finished (likely due to running out of memory)
