[2023-03-22T16:29:43.140-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T16:29:43.146-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-21T00:00:00+00:00 [queued]>
[2023-03-22T16:29:43.146-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:29:43.146-0400] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-22T16:29:43.146-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:29:43.151-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): api_sensor> on 2023-03-21 00:00:00+00:00
[2023-03-22T16:29:43.154-0400] {standard_task_runner.py:55} INFO - Started process 75613 to run task
[2023-03-22T16:29:43.157-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_api_connection', 'api_sensor', 'scheduled__2023-03-21T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/cities.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpke0cxqei']
[2023-03-22T16:29:43.158-0400] {standard_task_runner.py:83} INFO - Job 47: Subtask api_sensor
[2023-03-22T16:29:43.189-0400] {task_command.py:388} INFO - Running <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-21T00:00:00+00:00 [running]> on host sunandas-laptop.local
[2023-03-22T16:29:43.211-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_api_connection
AIRFLOW_CTX_TASK_ID=api_sensor
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T00:00:00+00:00
[2023-03-22T16:29:43.212-0400] {http.py:122} INFO - Poking: weather?q=cities,states,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T16:29:43.214-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T16:30:23.382-0400] {local_task_job.py:272} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-03-22T16:30:23.389-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 75613. PIDs of all processes in the group: [75613]
[2023-03-22T16:30:23.389-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 75613
[2023-03-22T16:31:23.430-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=75613, name='Python', status='running', started='16:29:43') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T16:31:23.430-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 75613
[2023-03-22T16:31:23.432-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=75613, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:29:43') (75613) terminated with exit code Negsignal.SIGKILL
[2023-03-22T16:31:23.433-0400] {standard_task_runner.py:168} ERROR - Job 47 was killed before it finished (likely due to running out of memory)
