[2023-03-22T16:38:40.205-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-22T16:38:40.210-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-22T16:38:40.210-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:38:40.210-0400] {taskinstance.py:1280} INFO - Starting attempt 5 of 1
[2023-03-22T16:38:40.210-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:38:40.220-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): api_sensor> on 2023-03-19 00:00:00+00:00
[2023-03-22T16:38:40.224-0400] {standard_task_runner.py:55} INFO - Started process 76211 to run task
[2023-03-22T16:38:40.226-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_api_connection', 'api_sensor', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/cities.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmpwgpko1at']
[2023-03-22T16:38:40.227-0400] {standard_task_runner.py:83} INFO - Job 58: Subtask api_sensor
[2023-03-22T16:38:40.245-0400] {task_command.py:388} INFO - Running <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [running]> on host sunandas-laptop.local
[2023-03-22T16:38:40.263-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_api_connection
AIRFLOW_CTX_TASK_ID=api_sensor
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-22T16:38:40.264-0400] {http.py:122} INFO - Poking: weather?q=cities,states,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T16:38:40.266-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T17:18:29.385-0400] {taskinstance.py:1073} INFO - Dependencies not met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-03-22T17:18:29.389-0400] {taskinstance.py:1073} INFO - Dependencies not met for <TaskInstance: my_api_connection.api_sensor scheduled__2023-03-19T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-03-22T17:18:29.392-0400] {local_task_job.py:147} INFO - Task is not able to be run
