[2023-03-22T16:31:25.510-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor manual__2023-03-22T19:55:36.510098+00:00 [queued]>
[2023-03-22T16:31:25.516-0400] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_api_connection.api_sensor manual__2023-03-22T19:55:36.510098+00:00 [queued]>
[2023-03-22T16:31:25.516-0400] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:31:25.516-0400] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-22T16:31:25.516-0400] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T16:31:25.520-0400] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): api_sensor> on 2023-03-22 19:55:36.510098+00:00
[2023-03-22T16:31:25.523-0400] {standard_task_runner.py:55} INFO - Started process 75724 to run task
[2023-03-22T16:31:25.526-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_api_connection', 'api_sensor', 'manual__2023-03-22T19:55:36.510098+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/cities.py', '--cfg-path', '/var/folders/71/zhs_yc7n05l7c97rnhn92bb80000gn/T/tmp7onqjshu']
[2023-03-22T16:31:25.527-0400] {standard_task_runner.py:83} INFO - Job 50: Subtask api_sensor
[2023-03-22T16:31:25.551-0400] {task_command.py:388} INFO - Running <TaskInstance: my_api_connection.api_sensor manual__2023-03-22T19:55:36.510098+00:00 [running]> on host sunandas-laptop.local
[2023-03-22T16:31:25.570-0400] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_api_connection
AIRFLOW_CTX_TASK_ID=api_sensor
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T19:55:36.510098+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T19:55:36.510098+00:00
[2023-03-22T16:31:25.571-0400] {http.py:122} INFO - Poking: weather?q=cities,states,US&units=standard&appid=94ca56afa3eee20f7100985fdfe682aa
[2023-03-22T16:31:25.573-0400] {base.py:73} INFO - Using connection ID 'my_api_connection' for task execution.
[2023-03-22T16:34:06.335-0400] {local_task_job.py:272} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2023-03-22T16:34:06.342-0400] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 75724. PIDs of all processes in the group: [75724]
[2023-03-22T16:34:06.342-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 75724
[2023-03-22T16:35:06.363-0400] {process_utils.py:147} WARNING - process psutil.Process(pid=75724, name='Python', status='running', started='16:31:25') did not respond to SIGTERM. Trying SIGKILL
[2023-03-22T16:35:06.364-0400] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 75724
[2023-03-22T16:35:06.380-0400] {process_utils.py:79} INFO - Process psutil.Process(pid=75724, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:31:25') (75724) terminated with exit code Negsignal.SIGKILL
[2023-03-22T16:35:06.381-0400] {standard_task_runner.py:168} ERROR - Job 50 was killed before it finished (likely due to running out of memory)
